language: javascript
script: phantomjs test.js
sudo: false
notifications:
  email: false
  slack:
    secure: PmQh6Vc9QDuBW5kbxGN/BfqP5Jc2kuHQ5xxALAF5W2Wv0U0NPmARbxqwRpUiSjl0fvboWEusPID+CnIebSZvuRXawkXDFo7xmQiUEHMHcf3Jo6CNhMJs2dp/82mnimOpkxXRBiBT9ZC4D1yjIPBtqqfe/qJPVxazL/c1EU7WA5I=
branches:
  only:
  - gh-pages
  - "/.+/"
